services:
  user-service:
    build: .
    ports:
      - "6004:6000"
    depends_on:
      - postgres
    command: sh -c "/wait && /server"
    environment:
      - POSTGRES_HOST=postgres
      - WAIT_HOSTS=postgres:5432

  postgres:
    image: "postgres:13-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    external: true
    name: evleria-trading_pg-data
